name: Windows RDP - Final Version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download and Configure Ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          ./ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          
      - name: Enable RDP and Set User Password
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 20 | ForEach-Object {[char]$_})
          $user = "Administrator"
          net user $user $password
          echo "RDP_USER=$user" >> $env:GITHUB_ENV
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Start Ngrok Tunnel as a Background Job
        run: Start-Job -ScriptBlock { ./ngrok.exe tcp 3389 }
        
      - name: Get RDP Connection Info
        run: |
          Start-Sleep -Seconds 30
          $tunnels = (Invoke-WebRequest http://127.0.0.1:4040/api/tunnels).Content | ConvertFrom-Json | Select-Object -ExpandProperty tunnels
          $rdpAddress = ($tunnels | Where-Object { $_.proto -eq 'tcp' } | Select-Object -ExpandProperty public_url)
          echo "========================================================================="
          echo "RDP Address: $rdpAddress"
          echo "User: ${{ env.RDP_USER }}"
          echo "Password: ${{ env.RDP_PASSWORD }}"
          echo "========================================================================="
          
      - name: Keep Server Alive
        run: Start-Sleep -Seconds 21000
