name: Windows rust desk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download RustDesk
      run: |
        Invoke-WebRequest -Uri https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x64.zip -OutFile rustdesk.zip
        Expand-Archive -Path .\rustdesk.zip -DestinationPath .
        
    - name: Run RustDesk
      run: ./rustdesk.exe --server 1.1.1.1
