name: Windows RDP - Ultimate Fix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Ngrok and RDP
        run: |
          # Download and extract Ngrok
          Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          
          # Find ngrok.exe dynamically and add its location to the PATH
          $ngrokPath = (Get-ChildItem -Recurse -Filter "ngrok.exe").FullName
          $env:PATH = "$(Split-Path -Path $ngrokPath -Parent);" + $env:PATH
          
          # Configure Ngrok authtoken
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          
          # Enable RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # Set password for Administrator
          $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 20 | ForEach-Object {[char]$_})
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV
          net user Administrator $password

      - name: Start Ngrok Tunnel and Display Info
        run: |
          # Start ngrok as a background job (now it's in the PATH)
          Start-Job -ScriptBlock { ngrok tcp 3389 }
          
          # Wait for ngrok to initialize
          Start-Sleep -Seconds 20
          
          # Get and display connection info
          $tunnels = (Invoke-WebRequest http://127.0.0.1:4040/api/tunnels).Content | ConvertFrom-Json | Select-Object -ExpandProperty tunnels
          $rdpAddress = ($tunnels | Where-Object { $_.proto -eq 'tcp' } | Select-Object -ExpandProperty public_url)
          echo "========================================================================="
          echo "RDP Address: $rdpAddress"
          echo "User: Administrator"
          echo "Password: ${{ env.RDP_PASSWORD }}"
          echo "========================================================================="
          
      - name: Keep Workflow Alive
        run: Start-Sleep -Seconds 21000
