name: Windows RDP

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Files and RDP
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
      - name: Set User Password
        run: |
          $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 20 | ForEach-Object {[char]$_})
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV
          net user Administrator $password
          
      - name: Start Tunnel
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ./ngrok.exe authtoken $env:NGROK_AUTH_TOKEN
          ./ngrok.exe tcp 3389 --log "stdout" > ngrok.log &
          
      - name: Get Connection Info
        run: |
          Start-Sleep -Seconds 15
          $tunnels = (Invoke-WebRequest http://127.0.0.1:4040/api/tunnels).Content | ConvertFrom-Json | Select-Object -ExpandProperty tunnels
          $rdpAddress = ($tunnels | Where-Object { $_.proto -eq 'tcp' } | Select-Object -ExpandProperty public_url)
          echo "========================================================================="
          echo "RDP Address: $rdpAddress"
          echo "User: Administrator"
          echo "Password: ${{ env.RDP_PASSWORD }}"
          echo "========================================================================="
          
      - name: Keep Workflow Alive
        run: Start-Sleep -Seconds 21000
