name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: Download Ngrok & Set Account
        run: |
          echo "NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}" >> $env:GITHUB_ENV
          Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
      
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          
      - name: Create Tunnel
        run: Start-Process Powershell -ArgumentList '-NoExit', '-Command', './ngrok.exe tcp 3389'
        
      - name: Set Password & Get Connection Info
        run: |
          Start-Sleep -Seconds 30
          $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 20 | ForEach-Object {[char]$_})
          $user = "Administrator"
          net user $user $password
          
          echo "RDP Address:"
          (Invoke-WebRequest http://127.0.0.1:4040/api/tunnels).Content | ConvertFrom-Json | Select-Object -ExpandProperty tunnels | Select-Object -ExpandProperty public_url
          echo "========================================================================="
          echo "User: $user"
          echo "Password: $password"
          echo "========================================================================="
          
      - name: Keep Alive
        run: |
          Start-Sleep -Seconds 99999
